-- ============================================================
-- SKEMA 1: SISTEM PERPUSTAKAAN MULTI-CABANG
-- DBMS      : PostgreSQL 14+
-- Tujuan    : Dataset OLAP untuk 7 soal analitik perpustakaan
-- Catatan   : Data waktu dibuat relatif terhadap CURRENT_DATE,
--             sehingga analisis 12 bulan terakhir tetap relevan.
-- ============================================================

DROP SCHEMA IF EXISTS perpustakaan CASCADE;
CREATE SCHEMA perpustakaan;
SET search_path TO perpustakaan, public;

-- ============================================================
-- 1. TABEL MASTER WILAYAH DAN ALAMAT
-- ============================================================

CREATE TABLE provinsi (
    provinsi_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_provinsi    varchar(100) NOT NULL UNIQUE,
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE kota (
    kota_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_kota        varchar(100) NOT NULL,
    provinsi_id      integer NOT NULL REFERENCES provinsi(provinsi_id),
    last_update      timestamp NOT NULL DEFAULT current_timestamp,
    UNIQUE (nama_kota, provinsi_id)
);

CREATE TABLE alamat (
    alamat_id        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alamat           varchar(200) NOT NULL,
    alamat2          varchar(200),
    kecamatan        varchar(100) NOT NULL,
    kota_id          integer NOT NULL REFERENCES kota(kota_id),
    kode_pos         varchar(10),
    telepon          varchar(30),
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

-- ============================================================
-- 2. TABEL CABANG, PETUGAS, ANGGOTA
-- ============================================================

CREATE TABLE cabang (
    cabang_id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_cabang          varchar(120) NOT NULL UNIQUE,
    kepala_petugas_id    integer,
    alamat_id            integer NOT NULL REFERENCES alamat(alamat_id),
    tanggal_dibuka       date NOT NULL,
    aktif                boolean NOT NULL DEFAULT true,
    last_update          timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE petugas (
    petugas_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_depan       varchar(80) NOT NULL,
    nama_belakang    varchar(80),
    email            varchar(150) NOT NULL UNIQUE,
    alamat_id        integer NOT NULL REFERENCES alamat(alamat_id),
    cabang_id        integer NOT NULL REFERENCES cabang(cabang_id),
    username         varchar(80) NOT NULL UNIQUE,
    password_hash    varchar(255) NOT NULL,
    aktif            boolean NOT NULL DEFAULT true,
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE anggota (
    anggota_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_anggota    varchar(30) NOT NULL UNIQUE,
    cabang_id        integer NOT NULL REFERENCES cabang(cabang_id),
    nama_depan       varchar(80) NOT NULL,
    nama_belakang    varchar(80),
    email            varchar(150) NOT NULL UNIQUE,
    alamat_id        integer NOT NULL REFERENCES alamat(alamat_id),
    tanggal_daftar   date NOT NULL,
    aktif            boolean NOT NULL DEFAULT true,
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

-- ============================================================
-- 3. TABEL BUKU, KATEGORI, PENULIS, PENERBIT
-- ============================================================

CREATE TABLE kategori (
    kategori_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama              varchar(100) NOT NULL UNIQUE,
    last_update       timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE penerbit (
    penerbit_id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama             varchar(150) NOT NULL UNIQUE,
    alamat_id        integer NOT NULL REFERENCES alamat(alamat_id),
    email            varchar(150),
    telepon          varchar(30),
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE penulis (
    penulis_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_depan       varchar(80) NOT NULL,
    nama_belakang    varchar(80),
    negara_asal      varchar(80),
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE buku (
    buku_id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    judul            varchar(250) NOT NULL,
    isbn             varchar(20) NOT NULL UNIQUE,
    tahun_terbit     integer NOT NULL CHECK (tahun_terbit BETWEEN 1900 AND 2100),
    penerbit_id      integer NOT NULL REFERENCES penerbit(penerbit_id),
    jumlah_halaman   integer NOT NULL CHECK (jumlah_halaman > 0),
    bahasa           varchar(50) NOT NULL DEFAULT 'Indonesia',
    sinopsis         text,
    aktif            boolean NOT NULL DEFAULT true,
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE buku_kategori (
    buku_id          integer NOT NULL REFERENCES buku(buku_id) ON DELETE CASCADE,
    kategori_id      integer NOT NULL REFERENCES kategori(kategori_id),
    last_update      timestamp NOT NULL DEFAULT current_timestamp,
    PRIMARY KEY (buku_id, kategori_id)
);

CREATE TABLE buku_penulis (
    buku_id          integer NOT NULL REFERENCES buku(buku_id) ON DELETE CASCADE,
    penulis_id       integer NOT NULL REFERENCES penulis(penulis_id),
    urutan_penulis   smallint NOT NULL DEFAULT 1 CHECK (urutan_penulis > 0),
    last_update      timestamp NOT NULL DEFAULT current_timestamp,
    PRIMARY KEY (buku_id, penulis_id)
);

-- ============================================================
-- 4. TABEL EKSEMPLAR, PEMINJAMAN, PEMBAYARAN DENDA
-- ============================================================

CREATE TABLE eksemplar (
    eksemplar_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_eksemplar   varchar(40) NOT NULL UNIQUE,
    buku_id          integer NOT NULL REFERENCES buku(buku_id),
    cabang_id        integer NOT NULL REFERENCES cabang(cabang_id),
    kode_rak         varchar(30) NOT NULL,
    tanggal_perolehan date NOT NULL,
    status           varchar(20) NOT NULL DEFAULT 'tersedia'
                     CHECK (status IN ('tersedia', 'dipinjam', 'rusak', 'hilang', 'perawatan')),
    last_update      timestamp NOT NULL DEFAULT current_timestamp
);

CREATE TABLE peminjaman (
    peminjaman_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal_pinjam       timestamp NOT NULL,
    tanggal_jatuh_tempo  timestamp NOT NULL,
    eksemplar_id         integer NOT NULL REFERENCES eksemplar(eksemplar_id),
    anggota_id           integer NOT NULL REFERENCES anggota(anggota_id),
    petugas_id           integer NOT NULL REFERENCES petugas(petugas_id),
    tanggal_kembali      timestamp,
    status               varchar(20) NOT NULL
                         CHECK (status IN ('dipinjam', 'dikembalikan', 'terlambat', 'hilang')),
    last_update          timestamp NOT NULL DEFAULT current_timestamp,
    CHECK (tanggal_jatuh_tempo > tanggal_pinjam),
    CHECK (tanggal_kembali IS NULL OR tanggal_kembali >= tanggal_pinjam)
);

CREATE TABLE pembayaran_denda (
    pembayaran_id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    peminjaman_id    bigint NOT NULL REFERENCES peminjaman(peminjaman_id) ON DELETE CASCADE,
    anggota_id       integer NOT NULL REFERENCES anggota(anggota_id),
    petugas_id       integer NOT NULL REFERENCES petugas(petugas_id),
    jumlah           numeric(12,2) NOT NULL CHECK (jumlah > 0),
    tanggal_bayar    timestamp NOT NULL,
    metode           varchar(30) NOT NULL
                     CHECK (metode IN ('tunai', 'kartu_debit', 'transfer_bank', 'dompet_digital')),
    status           varchar(20) NOT NULL
                     CHECK (status IN ('berhasil', 'tertunda', 'dibatalkan')),
    last_update      timestamp NOT NULL DEFAULT current_timestamp,
    UNIQUE (peminjaman_id)
);

-- FK kepala cabang ditambahkan setelah tabel petugas tersedia.
ALTER TABLE cabang
    ADD CONSTRAINT fk_cabang_kepala_petugas
    FOREIGN KEY (kepala_petugas_id) REFERENCES petugas(petugas_id);

-- ============================================================
-- 5. INDEKS UNTUK KEBUTUHAN OLAP
-- ============================================================

CREATE INDEX idx_anggota_cabang_aktif
    ON anggota (cabang_id, aktif);

CREATE INDEX idx_anggota_tanggal_daftar
    ON anggota (tanggal_daftar);

CREATE INDEX idx_eksemplar_buku_cabang
    ON eksemplar (buku_id, cabang_id);

CREATE INDEX idx_peminjaman_tanggal
    ON peminjaman (tanggal_pinjam);

CREATE INDEX idx_peminjaman_anggota_tanggal
    ON peminjaman (anggota_id, tanggal_pinjam);

CREATE INDEX idx_peminjaman_eksemplar
    ON peminjaman (eksemplar_id);

CREATE INDEX idx_pembayaran_denda_tanggal
    ON pembayaran_denda (tanggal_bayar);

CREATE INDEX idx_buku_kategori_kategori
    ON buku_kategori (kategori_id, buku_id);

-- ============================================================
-- 6. DATA MASTER
-- ============================================================

INSERT INTO provinsi (provinsi_id, nama_provinsi) VALUES
    (1, 'Aceh'),
    (2, 'Sumatera Utara'),
    (3, 'Jawa Barat');

INSERT INTO kota (kota_id, nama_kota, provinsi_id) VALUES
    (1, 'Banda Aceh', 1),
    (2, 'Meulaboh', 1),
    (3, 'Lhokseumawe', 1),
    (4, 'Medan', 2),
    (5, 'Binjai', 2),
    (6, 'Bandung', 3),
    (7, 'Bogor', 3),
    (8, 'Bekasi', 3);

INSERT INTO alamat (
    alamat_id, alamat, alamat2, kecamatan, kota_id, kode_pos, telepon
)
SELECT
    g,
    'Jalan Analitik Nomor ' || g,
    CASE WHEN g % 5 = 0 THEN 'Gedung ' || chr(65 + (g % 20)) ELSE NULL END,
    'Kecamatan ' || (((g - 1) % 16) + 1),
    ((g - 1) % 8) + 1,
    lpad((23000 + g)::text, 5, '0'),
    '08' || lpad((1000000000 + g)::text, 10, '0')
FROM generate_series(1, 900) AS g;

INSERT INTO cabang (
    cabang_id, nama_cabang, alamat_id, tanggal_dibuka, aktif
) VALUES
    (1, 'Perpustakaan Pusat Banda Aceh', 1, DATE '2012-01-10', true),
    (2, 'Perpustakaan Cabang Meulaboh', 2, DATE '2013-03-15', true),
    (3, 'Perpustakaan Cabang Lhokseumawe', 3, DATE '2014-06-20', true),
    (4, 'Perpustakaan Cabang Medan', 4, DATE '2015-08-12', true),
    (5, 'Perpustakaan Cabang Binjai', 5, DATE '2016-02-18', true),
    (6, 'Perpustakaan Cabang Bandung', 6, DATE '2017-04-22', true),
    (7, 'Perpustakaan Cabang Bogor', 7, DATE '2018-07-05', true),
    (8, 'Perpustakaan Cabang Bekasi', 8, DATE '2019-09-11', true);

INSERT INTO petugas (
    petugas_id, nama_depan, nama_belakang, email, alamat_id,
    cabang_id, username, password_hash, aktif
)
SELECT
    g,
    'Petugas' || g,
    'Perpustakaan',
    'petugas' || g || '@library.test',
    18 + g,
    ((g - 1) / 2) + 1,
    'petugas' || g,
    md5('password-petugas-' || g),
    true
FROM generate_series(1, 16) AS g;

UPDATE cabang
SET kepala_petugas_id = ((cabang_id - 1) * 2) + 1;

INSERT INTO penerbit (
    penerbit_id, nama, alamat_id, email, telepon
)
SELECT
    g,
    'Penerbit Wawasan ' || g,
    8 + g,
    'penerbit' || g || '@publisher.test',
    '021-555-' || lpad(g::text, 4, '0')
FROM generate_series(1, 10) AS g;

INSERT INTO penulis (
    penulis_id, nama_depan, nama_belakang, negara_asal
)
SELECT
    g,
    'Penulis' || g,
    CASE WHEN g % 3 = 0 THEN 'Nusantara' ELSE 'Cendekia' END,
    CASE
        WHEN g % 4 = 0 THEN 'Malaysia'
        WHEN g % 5 = 0 THEN 'Singapura'
        ELSE 'Indonesia'
    END
FROM generate_series(1, 40) AS g;

INSERT INTO kategori (kategori_id, nama) VALUES
    (1, 'Teknologi Informasi'),
    (2, 'Ekonomi dan Bisnis'),
    (3, 'Pendidikan'),
    (4, 'Sosial dan Humaniora'),
    (5, 'Sains Terapan'),
    (6, 'Kesehatan'),
    (7, 'Sastra dan Bahasa'),
    (8, 'Sejarah dan Budaya');

INSERT INTO buku (
    buku_id, judul, isbn, tahun_terbit, penerbit_id,
    jumlah_halaman, bahasa, sinopsis, aktif
)
SELECT
    g,
    CASE ((g - 1) / 10) + 1
        WHEN 1 THEN 'Teknologi Data Volume ' || lpad(g::text, 2, '0')
        WHEN 2 THEN 'Strategi Bisnis Volume ' || lpad(g::text, 2, '0')
        WHEN 3 THEN 'Inovasi Pendidikan Volume ' || lpad(g::text, 2, '0')
        WHEN 4 THEN 'Kajian Sosial Volume ' || lpad(g::text, 2, '0')
        WHEN 5 THEN 'Sains Terapan Volume ' || lpad(g::text, 2, '0')
        WHEN 6 THEN 'Ilmu Kesehatan Volume ' || lpad(g::text, 2, '0')
        WHEN 7 THEN 'Sastra Nusantara Volume ' || lpad(g::text, 2, '0')
        ELSE 'Sejarah Budaya Volume ' || lpad(g::text, 2, '0')
    END,
    '978602' || lpad(g::text, 7, '0'),
    2010 + (g % 16),
    ((g - 1) % 10) + 1,
    140 + ((g * 17) % 460),
    CASE WHEN g % 9 = 0 THEN 'Inggris' ELSE 'Indonesia' END,
    'Buku sintetis untuk latihan analitik PostgreSQL nomor ' || g || '.',
    true
FROM generate_series(1, 80) AS g;

INSERT INTO buku_kategori (buku_id, kategori_id)
SELECT
    buku_id,
    ((buku_id - 1) / 10) + 1
FROM buku;

INSERT INTO buku_penulis (buku_id, penulis_id, urutan_penulis)
SELECT
    buku_id,
    ((buku_id - 1) % 40) + 1,
    1
FROM buku;

INSERT INTO buku_penulis (buku_id, penulis_id, urutan_penulis)
SELECT
    buku_id,
    ((buku_id + 12) % 40) + 1,
    2
FROM buku
WHERE buku_id % 5 = 0;

-- Setiap buku memiliki dua eksemplar pada cabang utama.
-- Sebagian buku memiliki satu eksemplar tambahan pada cabang kedua.
WITH copy_rows AS (
    SELECT
        b.buku_id,
        CASE
            WHEN b.buku_id <= 60 THEN ((b.buku_id - 1) % 5) + 1
            ELSE 6 + ((b.buku_id - 61) % 3)
        END AS cabang_id,
        gs AS copy_no
    FROM buku AS b
    CROSS JOIN generate_series(1, 2) AS gs

    UNION ALL

    SELECT
        b.buku_id,
        CASE
            WHEN b.buku_id <= 60 THEN
                CASE
                    WHEN (((b.buku_id - 1) % 5) + 1) = 5 THEN 1
                    ELSE (((b.buku_id - 1) % 5) + 2)
                END
            ELSE
                CASE
                    WHEN (6 + ((b.buku_id - 61) % 3)) = 8 THEN 6
                    ELSE (7 + ((b.buku_id - 61) % 3))
                END
        END AS cabang_id,
        3 AS copy_no
    FROM buku AS b
    WHERE b.buku_id % 4 = 0
), numbered AS (
    SELECT
        row_number() OVER (ORDER BY buku_id, cabang_id, copy_no) AS eksemplar_id,
        buku_id,
        cabang_id,
        copy_no
    FROM copy_rows
)
INSERT INTO eksemplar (
    eksemplar_id, kode_eksemplar, buku_id, cabang_id,
    kode_rak, tanggal_perolehan, status
)
SELECT
    eksemplar_id,
    'EKS-' || lpad(buku_id::text, 3, '0') || '-' || cabang_id || '-' || copy_no,
    buku_id,
    cabang_id,
    'R-' || lpad((((buku_id - 1) % 20) + 1)::text, 2, '0'),
    current_date - ((buku_id * 13 + copy_no * 7) % 2500),
    'tersedia'
FROM numbered;

-- 720 anggota dibagi ke 12 cohort pendaftaran, masing-masing 60 anggota.
-- Setiap cabang memiliki 90 anggota, sehingga soal agregasi cabang terisi baik.
INSERT INTO anggota (
    anggota_id, nomor_anggota, cabang_id, nama_depan, nama_belakang,
    email, alamat_id, tanggal_daftar, aktif
)
SELECT
    g,
    'AGT-' || lpad(g::text, 5, '0'),
    ((g - 1) % 8) + 1,
    'Anggota' || g,
    CASE WHEN g % 2 = 0 THEN 'Utama' ELSE 'Cendekia' END,
    'anggota' || g || '@member.test',
    100 + g,
    (
        date_trunc('month', current_date)
        - (15 - ((g - 1) / 60)) * interval '1 month'
        + (((g - 1) % 20) + 1) * interval '1 day'
    )::date,
    (g % 13 <> 0)
FROM generate_series(1, 720) AS g;

-- ============================================================
-- 7. DATA TRANSAKSI PEMINJAMAN
-- ============================================================

-- 7.1 Peminjaman dasar selama 15 bulan.
-- Pola popularitas sengaja bervariasi agar ranking dan persentil bermakna.
WITH months AS (
    SELECT
        gs AS month_idx,
        (
            date_trunc('month', current_date)
            - (14 - gs) * interval '1 month'
        )::date AS month_start
    FROM generate_series(0, 14) AS gs
), book_month_plan AS (
    SELECT
        b.buku_id,
        m.month_idx,
        m.month_start,
        CASE
            WHEN b.buku_id <= 60 THEN ((b.buku_id - 1) % 5) + 1
            ELSE 6 + ((b.buku_id - 61) % 3)
        END AS cabang_id,
        (
            1
            + ((b.buku_id + m.month_idx * 2) % 5)
            + CASE WHEN (b.buku_id % 10) IN (9, 0) THEN 4 ELSE 0 END
        )::integer AS loan_count
    FROM buku AS b
    CROSS JOIN months AS m
), expanded AS (
    SELECT
        p.*,
        occ
    FROM book_month_plan AS p
    CROSS JOIN LATERAL generate_series(1, p.loan_count) AS occ
    WHERE NOT (
        (p.cabang_id = 8 AND p.month_idx = 8)
        OR (p.cabang_id = 7 AND p.month_idx = 5)
    )
), member_choice AS (
    SELECT
        e.*,
        e.cabang_id + 8 * ((e.buku_id * 7 + e.month_idx * 11 + e.occ * 13) % 90) AS raw_anggota_id
    FROM expanded AS e
), prepared AS (
    SELECT
        mc.*,
        CASE
            WHEN mc.raw_anggota_id <= 10 THEN mc.raw_anggota_id + 80
            ELSE mc.raw_anggota_id
        END AS anggota_id,
        (
            mc.month_start
            + ((mc.buku_id + mc.occ * 3) % 24) * interval '1 day'
            + ((mc.occ * 17) % 10) * interval '1 hour'
        ) AS tanggal_pinjam
    FROM member_choice AS mc
)
INSERT INTO peminjaman (
    tanggal_pinjam, tanggal_jatuh_tempo, eksemplar_id,
    anggota_id, petugas_id, tanggal_kembali, status
)
SELECT
    p.tanggal_pinjam,
    p.tanggal_pinjam + interval '14 days',
    e.eksemplar_id,
    p.anggota_id,
    ((p.cabang_id - 1) * 2) + 1 + ((p.occ - 1) % 2),
    p.tanggal_pinjam + (7 + ((p.buku_id + p.occ + p.month_idx) % 13)) * interval '1 day',
    CASE
        WHEN (7 + ((p.buku_id + p.occ + p.month_idx) % 13)) > 14 THEN 'terlambat'
        ELSE 'dikembalikan'
    END
FROM prepared AS p
JOIN LATERAL (
    SELECT ek.eksemplar_id
    FROM eksemplar AS ek
    WHERE ek.buku_id = p.buku_id
      AND ek.cabang_id = p.cabang_id
    ORDER BY ek.eksemplar_id
    LIMIT 1
) AS e ON true;

-- 7.2 Peminjaman cohort untuk menguji retensi bulan ke-1, ke-2, dan ke-3.
WITH member_base AS (
    SELECT
        a.anggota_id,
        a.cabang_id,
        date_trunc('month', a.tanggal_daftar)::date AS cohort_month,
        ((a.anggota_id - 1) / 60) AS cohort_idx,
        ((a.anggota_id - 1) % 60) + 1 AS member_pos
    FROM anggota AS a
    WHERE a.anggota_id > 10
), retention_months AS (
    SELECT * FROM (VALUES (1), (2), (3)) AS v(month_no)
), retained AS (
    SELECT
        mb.*,
        rm.month_no,
        CASE
            WHEN mb.cabang_id <= 5 THEN
                mb.cabang_id + 5 * ((mb.anggota_id + rm.month_no * 3) % 12)
            WHEN mb.cabang_id = 6 THEN
                61 + 3 * ((mb.anggota_id + rm.month_no) % 7)
            WHEN mb.cabang_id = 7 THEN
                62 + 3 * ((mb.anggota_id + rm.month_no) % 7)
            ELSE
                63 + 3 * ((mb.anggota_id + rm.month_no) % 6)
        END AS buku_id
    FROM member_base AS mb
    CROSS JOIN retention_months AS rm
    WHERE
        CASE rm.month_no
            WHEN 1 THEN mb.member_pos <= 42 + (mb.cohort_idx % 4) * 3
            WHEN 2 THEN mb.member_pos <= 33 + (mb.cohort_idx % 3) * 4
            WHEN 3 THEN mb.member_pos <= 24 + (mb.cohort_idx % 5) * 3
        END
), prepared AS (
    SELECT
        r.*,
        (
            r.cohort_month
            + r.month_no * interval '1 month'
            + ((r.member_pos * 3 + r.month_no) % 20) * interval '1 day'
            + interval '10 hours'
        ) AS tanggal_pinjam
    FROM retained AS r
)
INSERT INTO peminjaman (
    tanggal_pinjam, tanggal_jatuh_tempo, eksemplar_id,
    anggota_id, petugas_id, tanggal_kembali, status
)
SELECT
    p.tanggal_pinjam,
    p.tanggal_pinjam + interval '14 days',
    e.eksemplar_id,
    p.anggota_id,
    ((p.cabang_id - 1) * 2) + 1,
    p.tanggal_pinjam + (8 + ((p.anggota_id + p.month_no) % 12)) * interval '1 day',
    CASE
        WHEN (8 + ((p.anggota_id + p.month_no) % 12)) > 14 THEN 'terlambat'
        ELSE 'dikembalikan'
    END
FROM prepared AS p
JOIN LATERAL (
    SELECT ek.eksemplar_id
    FROM eksemplar AS ek
    WHERE ek.buku_id = p.buku_id
      AND ek.cabang_id = p.cabang_id
    ORDER BY ek.eksemplar_id
    LIMIT 1
) AS e ON true;

-- 7.3 Sepuluh anggota dengan aktivitas sangat tinggi.
-- Mereka hanya meminjam buku 1-20 agar soal NOT EXISTS memiliki hasil jelas.
WITH extra_plan AS (
    SELECT
        member_id,
        n,
        1 + ((member_id * 3 + n) % 20) AS buku_id,
        (
            date_trunc('month', current_date)
            - ((n - 1) % 15) * interval '1 month'
            + ((member_id * 2 + n) % 24) * interval '1 day'
            + interval '14 hours'
        ) AS tanggal_pinjam
    FROM generate_series(1, 10) AS member_id
    CROSS JOIN generate_series(1, 60) AS n
), prepared AS (
    SELECT
        ep.*,
        ((ep.buku_id - 1) % 5) + 1 AS cabang_id
    FROM extra_plan AS ep
)
INSERT INTO peminjaman (
    tanggal_pinjam, tanggal_jatuh_tempo, eksemplar_id,
    anggota_id, petugas_id, tanggal_kembali, status
)
SELECT
    p.tanggal_pinjam,
    p.tanggal_pinjam + interval '14 days',
    e.eksemplar_id,
    p.member_id,
    ((p.cabang_id - 1) * 2) + 1,
    p.tanggal_pinjam + (10 + ((p.member_id + p.n) % 10)) * interval '1 day',
    CASE
        WHEN (10 + ((p.member_id + p.n) % 10)) > 14 THEN 'terlambat'
        ELSE 'dikembalikan'
    END
FROM prepared AS p
JOIN LATERAL (
    SELECT ek.eksemplar_id
    FROM eksemplar AS ek
    WHERE ek.buku_id = p.buku_id
      AND ek.cabang_id = p.cabang_id
    ORDER BY ek.eksemplar_id
    LIMIT 1
) AS e ON true;

-- 7.4 Buku 31 memiliki aktivitas denda tinggi, tetapi tidak pernah dipinjam
-- oleh sepuluh anggota teraktif. Ini membuat soal pendapatan denda bermakna.
WITH special_plan AS (
    SELECT
        n,
        1 + 8 * ((n * 7) % 90) AS raw_anggota_id,
        (
            date_trunc('month', current_date)
            - ((n - 1) % 12) * interval '1 month'
            + ((n * 5) % 24) * interval '1 day'
            + interval '11 hours'
        ) AS tanggal_pinjam
    FROM generate_series(1, 50) AS n
), prepared AS (
    SELECT
        n,
        CASE WHEN raw_anggota_id <= 10 THEN raw_anggota_id + 80 ELSE raw_anggota_id END AS anggota_id,
        tanggal_pinjam
    FROM special_plan
)
INSERT INTO peminjaman (
    tanggal_pinjam, tanggal_jatuh_tempo, eksemplar_id,
    anggota_id, petugas_id, tanggal_kembali, status
)
SELECT
    p.tanggal_pinjam,
    p.tanggal_pinjam + interval '14 days',
    e.eksemplar_id,
    p.anggota_id,
    1,
    p.tanggal_pinjam + interval '25 days',
    'terlambat'
FROM prepared AS p
JOIN LATERAL (
    SELECT ek.eksemplar_id
    FROM eksemplar AS ek
    WHERE ek.buku_id = 31
      AND ek.cabang_id = 1
    ORDER BY ek.eksemplar_id
    LIMIT 1
) AS e ON true;

-- 7.5 Buku 65 dibuat populer pada cabang 7 agar analisis buku yang hanya
-- tersedia di cabang non-top-5 memiliki kandidat yang jelas.
WITH special_plan AS (
    SELECT
        n,
        7 + 8 * ((n * 11) % 90) AS raw_anggota_id,
        (
            date_trunc('month', current_date)
            - ((n - 1) % 12) * interval '1 month'
            + ((n * 7) % 24) * interval '1 day'
            + interval '15 hours'
        ) AS tanggal_pinjam
    FROM generate_series(1, 120) AS n
), prepared AS (
    SELECT
        n,
        CASE WHEN raw_anggota_id <= 10 THEN raw_anggota_id + 80 ELSE raw_anggota_id END AS anggota_id,
        tanggal_pinjam
    FROM special_plan
)
INSERT INTO peminjaman (
    tanggal_pinjam, tanggal_jatuh_tempo, eksemplar_id,
    anggota_id, petugas_id, tanggal_kembali, status
)
SELECT
    p.tanggal_pinjam,
    p.tanggal_pinjam + interval '14 days',
    e.eksemplar_id,
    p.anggota_id,
    13,
    p.tanggal_pinjam + (8 + (p.n % 10)) * interval '1 day',
    CASE WHEN (8 + (p.n % 10)) > 14 THEN 'terlambat' ELSE 'dikembalikan' END
FROM prepared AS p
JOIN LATERAL (
    SELECT ek.eksemplar_id
    FROM eksemplar AS ek
    WHERE ek.buku_id = 65
      AND ek.cabang_id = 7
    ORDER BY ek.eksemplar_id
    LIMIT 1
) AS e ON true;

-- Memastikan terdapat bulan nol transaksi pada cabang 7 dan 8.
-- Hal ini diperlukan untuk menguji calendar spine pada soal pertumbuhan bulanan.
DELETE FROM peminjaman AS p
USING eksemplar AS e
WHERE p.eksemplar_id = e.eksemplar_id
  AND (
        (
            e.cabang_id = 8
            AND date_trunc('month', p.tanggal_pinjam)
                = date_trunc('month', current_date) - interval '6 months'
        )
        OR
        (
            e.cabang_id = 7
            AND date_trunc('month', p.tanggal_pinjam)
                = date_trunc('month', current_date) - interval '9 months'
        )
      );

-- ============================================================
-- 8. DATA PEMBAYARAN DENDA
-- ============================================================

INSERT INTO pembayaran_denda (
    peminjaman_id, anggota_id, petugas_id, jumlah,
    tanggal_bayar, metode, status
)
SELECT
    p.peminjaman_id,
    p.anggota_id,
    p.petugas_id,
    round(
        (
            ((p.tanggal_kembali::date - p.tanggal_jatuh_tempo::date) * 1.75)
            + CASE
                WHEN e.buku_id = 31 THEN 125.00
                WHEN e.buku_id <= 20 THEN 35.00
                ELSE 0.00
              END
        )::numeric,
        2
    ) AS jumlah,
    p.tanggal_kembali + interval '1 day',
    CASE (p.peminjaman_id % 4)
        WHEN 0 THEN 'tunai'
        WHEN 1 THEN 'kartu_debit'
        WHEN 2 THEN 'transfer_bank'
        ELSE 'dompet_digital'
    END,
    'berhasil'
FROM peminjaman AS p
JOIN eksemplar AS e
    ON e.eksemplar_id = p.eksemplar_id
WHERE p.tanggal_kembali IS NOT NULL
  AND p.tanggal_kembali::date > p.tanggal_jatuh_tempo::date;

-- ============================================================
-- 9. ANALYZE DAN VALIDASI RINGKAS
-- ============================================================

ANALYZE;

-- Ringkasan dataset. Hasilnya dapat dilihat saat script dijalankan di psql.
SELECT 'cabang' AS objek, count(*)::bigint AS jumlah FROM cabang
UNION ALL
SELECT 'anggota', count(*) FROM anggota
UNION ALL
SELECT 'buku', count(*) FROM buku
UNION ALL
SELECT 'eksemplar', count(*) FROM eksemplar
UNION ALL
SELECT 'peminjaman', count(*) FROM peminjaman
UNION ALL
SELECT 'pembayaran_denda', count(*) FROM pembayaran_denda
ORDER BY objek;

-- Setelah membuka koneksi baru, jalankan:
-- SET search_path TO perpustakaan, public;
